title: "Yihan Chen"
author: "Yihan Chen"
#description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Home}
  - {file: "README.md", title: Work Experience}
  - {file: "archive.html", title: Projects}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://yihan-chen-linguistics.github.io/portfolio/"}
  - {title: Email, icon: envelope, url: "mailto:yihan.chen@ufl.edu"}
  - {title: LinkedIn, icon: linkedin, url: "www.linkedin.com/in/yihan-chen-3627012a9"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
